### PR TITLE
The Dependency Manager now supports versioning and samples importing TRNG-1349

### PR DESCRIPTION
**Pull request by Gusinuhe**
### Description

The Dependency Manager can now install packages at specific version numbers and also import samples from the packages.

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

Either import the Creator to a new Unity project or go `Help > Reset Packages to defaults`, all packages should be retrieved properly.

### CODE REVIEW

**Comment by Luphoxa** [comment]
So before when resetting packages it grabbed the newest versions, and now it should reset the packages to the version that we specified before? So I guess this is most important for the XRI package right now, right?

**Comment by Gusinuhe** [comment]
> So before when resetting packages it grabbed the newest versions, and now it should reset the packages to the version that we specified before? So I guess this is most important for the XRI package right now, right?

Exactly, now a specific version can be used to load a unity package and if that package has samples that we want to automatically load into the project, we can do so.

This is used in the XR Interaction Component so the simulator and the default input mapping (for the new input system) can be loaded.

**Comment by SimonTheSourcerer** [comment]
git clone --single-branch --branch develop git@github.com:Innoactive/Basic-Conditions-And-Behaviors.git Innoactive/Creator/Components/Basic-ConditionsBehaviors
git clone --single-branch --branch develop git@github.com:Innoactive/Basic-Interaction-Component.git Innoactive/Creator/Components/Basic-Interaction
git clone --single-branch --branch develop git@github.com:Innoactive/Basic-UI-Component.git Innoactive/Creator/Components/Basic-UI-Components
git clone --single-branch --branch feature/arrow-mouse-movement git@github.com:Innoactive/Desktop-Interaction-Component.git Innoactive/Creator/Components/Desktop-Interaction
git clone --single-branch --branch develop git@github.com:Innoactive/TextToSpeech-Component.git Innoactive/Creator/Components/TextToSpeech
git clone --single-branch --branch feature/add-xri-simulator-support-TRNG-1299 git@github.com:Innoactive/XR-Interaction-Component.git Innoactive/Creator/Components/XR-Interaction-Component
git clone --single-branch --branch feature/versioning-and-samples-importing-for-the-dependency-manager-TRNG-1349 git@github.com:Innoactive/Creator.git Innoactive/Creator/Core
git clone --single-branch --branch develop git@github.com:Innoactive/IA-Training-Template.git Innoactive/Creator/IA-Training-Template

**Comment by Luphoxa** [comment]
I cloned all packages (took Simons list) into a new unity project and I am stuck at the point where I am importing the xr interaction toolkit :o Anybody experiencing similar problems?
image

**Review by SimonTheSourcerer — APPROVED** [review]
Tested it again, seems to work also the import window of eternal doom is gone too.

**Pull request merged**
