### PR TITLE
Feature/open course window

### PR DESCRIPTION
**Pull request by tomwim**
### Description
Introduces an "Open Course..." window which allows the user to open a training course for his/her current scene.

### Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Aditional Notes
User can choose from courses through a dropdown
image

Notifies the user if there are no courses existent in the project
image

Notifies the user if the current scene is not setup as a training scene
image

### CODE REVIEW

**Comment by tomwim** [comment]
This is only a draft for now! No need to review

**Comment by Gusinuhe** [comment]
Do we have a design for this? 

I think that if there is an `Open Course` feature and I am not in the scene it should open the scene with the course I selected.

**Comment by tomwim** [comment]
> Do we have a design for this?
> 
> I think that if there is an `Open Course` feature and I am not in the scene, it should open the scene with the course I selected.
> Also, maybe if there are no training courses available, this option should not be available.

If the current scene is not a training scene you get a error message as shown in the screenshots and same when you do not have any training courses in your project.

**Comment by Gusinuhe** [comment]
> > Do we have a design for this?
> 
> > 
> 
> > I think that if there is an `Open Course` feature and I am not in the scene, it should open the scene with the course I selected.
> 
> > Also, maybe if there are no training courses available, this option should not be available.
> 
> 
> 
> If the current scene is not a training scene you get a error message as shown in the screenshots and same when you do not have any training courses in your project.


I know, but UX-wise an `Open Course` feature that doesn't allow you to open a course feels pretty odd.

Users can already open a course different than the one that could be set in the scene in a training scene, what value does this feature add to the Creator?

**Comment by tomwim** [comment]
It does allow you to open a course and it does exactly that. It opens the Course Editor with the selected course in the current scene. A course is independent of a scene. I understand the idea of opening the scene and the course but there are also people who use the same course for different scenes (same objects and training course in a different environment).

And yes you can open a course through the Training Configuration but that is not where you would expect it. Users expect it at the same place where you can create a new course, which is in the toolbar. It makes a users life easier because he/she does not have to click through the hierarchy and find the Training Config.

**Comment by Gusinuhe** [comment]
User has one or several training courses in a Unity project.
User opens the unity project.
User tries to open a course with the `Open Course` feature.
The window is opened but the user is not allowed to open aby course.

Users expect things to work as they are called, the same way a user is mad if a fix button makes an object to fall in the floor.

**Comment by tomwim** [comment]
Oh Great @Gusinuhe , your concerns were heard and UX decided to look into this more to come to a better solution. Will put this PR on hold now!

**Comment by Gusinuhe** [comment]
image

**Comment by Luphoxa** [comment]
What's the status on this? :)

**Comment by tomwim** [comment]
> So it's been on hold for a while, any news about what will happen with this? :)

No nothing new for now, just on hold until further notice.

**Comment by tomwim** [comment]
Closed because no movement since August

**Pull request closed without merging**
