### PR TITLE
Feature/UI improvements

### PR DESCRIPTION
**Pull request by SimonTheSourcerer**

### CODE REVIEW

**Review by Gusinuhe — CHANGES_REQUESTED** [review]
There is a bunch of magic going on in `Editor/UI/Drawers/MetadataWrapperDrawer.cs` & `Editor/UI/Drawers/TransitionInstantiatiorDrawer.cs`

**Comment by Gusinuhe** [comment]
Btw, what should I test? Is there a list of the changes?

**Comment by SimonTheSourcerer** [comment]
Yes, there is a list of changes, see here:
image

**Review by Gusinuhe — APPROVED** [review]

**Review by JulieAtInnoactive — APPROVED** [review]
I have tested the branch, I did not review the code. I did not find any issues

**Review by Luphoxa — APPROVED** [review]

**Comment by Luphoxa** [comment]
I tested the branch with merged develop by recreating the charger training, seems to work well until now.

**Pull request merged**
