### PR TITLE
The Creator now always install requested XR SDK TRNG-1465

### PR DESCRIPTION
**Pull request by Gusinuhe**
### Description

The XR Plugin Management didn't expose any API to enable XR Loaders, we came up with a solution that required reflection to enable the XR SDK that the user selected in the wizard. The newest version of the package now exposes an API to properly load the XR Loaders and the legacy private method no longer works on old Unity 1029 LTS provoking these errors:

image

This PR addressed both issues.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Either try a new project, import the creator, and select any xr sdk or delete the XR folder (if present) and every folder at root but Assets and then open the project again, and select any xr sdk.

The selected SDK must always be enabled after the installation and no errors should be during the process.

### CODE REVIEW

**Comment by Gusinuhe** [comment]
> Test notes:
> I don't know exactly how it is supposed to work right or not so here my notes:
> 
> Oculus setup:
> 
> * no errors on setup or after setup
> * XR plugin Management version 4.0.1 got installed. When I try switching to an older version in the package manager it goes back to 4.0.1
> 
> HTC Vive Update:
> 
> * Here I don't get the XR plugin management package installed, instead I get the Open VR Desktop package installed. (Funnily enough, I get a warning that itis not installed). I assume this is right and we don't need the XR plugin management package here. I cannot change the version here in the package manager
> 
> Is this relevant for other Hardware settings than Oculus or did I misunderstand what you mean with choosing xr sdk in the wizard?
> 
> Config:
> Unity2019.4.19f
> all develop + this branch
> new project, no updated

That is exactly what this PR is supposed to do, ensure to always enable the desired XR SDK.
If it is Oculus or WindowsMR it installs the XR plugin Management version 4.0.1 and then the desired package, if it is OpenVR it then just enables the legacy VR configuration and the legacy OpenVR and Oculus packages (that is a default behavior when enabling OpenVR).

And yes, this is supposed to only use XR plugin Management v4.0.1 👍

**Comment by Luphoxa** [comment]
I am having a second look at this btw, will keep this comment as a placeholder for the summary of insights :)

**Comment by Gusinuhe** [comment]
> I am having a second look at this btw, will keep this comment as a placeholder for the summary of insights :)
> 
> `Config: Unity 2019.04.10f & all develop & not this PR`
> 
> * Could reproduce this error setting up Oculus in a new and an existing project
> * Could not reproduce this error setting up Windows MXR, HTC Vive
> 
> `Config: Unity 2019.04.10 & all develop & this PR`
> First of all, I had difficulties getting rid of a specific hardware setup, because resetting the packages does not work now, as it will reinstall everything missing. Not sure if this is actually a problem for clients though :)
> 
> I could recreate this bug by setting up Oculus in an existing project and a new project. I couldn't set it up manually afterward because the XR Plugin Settings were missing in my preferences somehow :o Any idea what I am missing here, maybe you have an idea what I could check?
> `My preferences`
> image
> `My packages`
> image
> 
> With the develop branch I still can go to the XR Plug-In Management to fix the bug manually by clicking on Oculus, but with the PR I can't.
> image

This issue is only present in old Unity version (see [here](https://spectrum.chat/innoactive-creator/getting-started/build-target-error-on-first-load~93ab2137-017c-4e48-8c6b-71855a3f141d?m=MTYxNDY3OTUxNzUxMQ==)].

The issue is due to some compilation error in the XR Plugin Management, nothing we can do there.

**Comment by Luphoxa** [comment]
I just find it concerning that fixing this bug in develop is way easier than with this PR. And I still don't know how exactly to do it, so it would be good to know how much effort it would take with this pr in comparison

**Comment by Gusinuhe** [comment]
But the issue was not fixed in develop, it was just recompiled and the editor was able to execute the xr plugin management again.

The original bug will always happen unless unity releases a new xr plugin management version with a fix for old unity LTS versions or using a newer unity version.

**Review by SimonTheSourcerer — APPROVED** [review]

**Comment by tomwim** [comment]
Tested it and got this in the end 👍 
image

Only think I noticed during testing was that when you import everything you are asked if you want to switch to the New Input System and restart Unity. If you click Yes the dialog closes, the Wizard opens, you can click through it, then when you hit Finished Unity will restart from the dialog before. Not a big deal, not part of this ticket but something that might be a bit odd to the user

**Review by tomwim — APPROVED** [review]

**Pull request merged**
